[env:esp32_32u]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.3

build_flags =
  -D MQTT_MAX_PACKET_SIZE=8192

[env:esp32_32u_ota]
platform = ${env:esp32_32u.platform}
board = ${env:esp32_32u.board}
framework = ${env:esp32_32u.framework}
monitor_speed = ${env:esp32_32u.monitor_speed}
lib_deps = ${env:esp32_32u.lib_deps}
build_flags = ${env:esp32_32u.build_flags}
upload_protocol = espota
upload_port = YOUR_DEVICE_IP
extra_scripts =
  scripts/ota_upload_flags.py
